### PR TITLE
Added vRY-Configurator

### PR DESCRIPTION
**Pull request by tanishqmanuja**
- Used InquirerPy package
- Can be called using cmd using "vry.exe --configure" or "python main.py --configure" while development

### CODE REVIEW

**Review by isaacKenyon — COMMENTED** [review]
Firstly, I ran vRY with no issue. Used the advanced config, applied the default value for PORT by simply hitting ENTER when prompted for a number; re-ran vRY to be greeted with the Firewall error message.

**Comment by tanishqmanuja** [comment]
Will look into it today and update the PR.

**Comment by tanishqmanuja** [comment]
Works fine for me now .. has anyone tested after recent commit?

**Comment by OwOHamper** [comment]
What about my review?

**Comment by tanishqmanuja** [comment]
> What about my review?
Fixed that problem.. its was due to string instead of int in port
,

**Comment by tanishqmanuja** [comment]
@OwOHamper, Have you made your review public.. only one review is showing here.
Screenshot_20220717-103339_Chrome~2

**Comment by OwOHamper** [comment]
image
hmmm I am not sure

**Comment by tanishqmanuja** [comment]
Your review wasn't published ig.. cannot see it still on GitHub but image will do. Will push new commit for the suggestions

**Comment by OwOHamper** [comment]
You got any idea how I can publish it? lol

**Comment by tanishqmanuja** [comment]
Same thing happened with decrypt so he can help . I never reviewed any PR myself so i cant help :(

**Comment by tanishqmanuja** [comment]
Done refactoring. Plus since table mod PR is closed, can you remove this(pretty table from main.py) from source as it is unused now.
image

**Comment by OwOHamper** [comment]
it would still break you would need to create double if statement because it would check both values and if sys.argv[1] is undefined the first condition would be False but second one would still be checked. And also in the bare except you should print what exactly went wrong or initialize logs before it and log it. If there was some error we wouldn't have idea what it is

**Comment by tanishqmanuja** [comment]
> it would still break you would need to create double if statement because it would check both values and if sys.argv[1] is undefined the first condition would be False but second one would still be checked. And also in the bare except you should print what exactly went wrong or initialize logs before it and log it. If there was some error we wouldn't have idea what it is

AFAIK and operator is short-circuited in python and javascript that means second condition os only evaluated if first is true so double if is not required. I have tested calling main.py with and without arguments and both cases have worked.
As for the bare except, you are right about the situation but I being a js dev have little to no knowledge about the exceptions in python .. will need your help on that.

**Comment by D3CRYPT360** [comment]
> You got any idea how I can publish it? lol
opera_q3EJkDRSRW

**Comment by tanishqmanuja** [comment]
> > You got any idea how I can publish it? lol
> > opera_q3EJkDRSRW
> >       
> >         [
> >           
> >             opera_q3EJkDRSRW
> >           
> >         ](https://user-images.githubusercontent.com/70775520/179400939-c8915b1f-287f-41f3-aeec-04d5248a36f3.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/70775520/179400939-c8915b1f-287f-41f3-aeec-04d5248a36f3.gif)

IDK but still only zay's review is showing

**Review by isaacKenyon — CHANGES_REQUESTED** [review]
Handling the input of  `no` for `proceed` under `src/configuator.py` would lead to a better UX since it currently throws an error.

**Review by isaacKenyon — APPROVED** [review]

**Pull request merged**
