### PR TITLE
Changes to propose

### PR DESCRIPTION
**Pull request by SuppliedOrange**
1) The preview is messed up and doesnt actually show what I changed, see https://www.diffchecker.com/rHzk0tkD to see differences.

2) I removed a line that was left out in the wild and wouldnt let you start the app directly from the code as mentioned in discord

3) Changed all references of 'peek' to 'peak', grammatical error.

4) Y no manual refresh :(

Cool app ily

### CODE REVIEW

**Comment by isaacKenyon** [comment]
All that is different from the main.py to the . exe is the removal of a block comment, that shouldn't affect anything.

@OwOHamper Will know more about this than me but im pretty sure we need that traceback import.

**Comment by isaacKenyon** [comment]
We've had some negative feedback with the automatic refresh, and to be honest, I'm not completely sure why. I've heard that manual is 'easier and less time consuming' but I thought that was the point of automatic, could you be more specific on why you liked manual so much?

also ily too

**Comment by SuppliedOrange** [comment]
ok

**Comment by OwOHamper** [comment]
1. Ye that was mess yesterday but I think you got bad version since the varaibles are still "peek", cooldown thing and the whole program is not in try and except
3. That was fixed
4. Manual refresh was always possible by typing "0" in the config

**Comment by OwOHamper** [comment]
Ima wait for your reply first

**Pull request closed without merging**
